version: 0.2
phases:
  pre_build:
    commands:
      - zip my-deployment-package.zip function.py
  build:
    commands:
      - aws cloudformation package --template-file unpacked.yaml --s3-bucket "lambda-pipeline-test" --output-template-file packed.yaml
artifacts:
  files:
  - unpacked.yaml
  - packed.yaml