Transform: AWS::Serverless-2016-10-31
Resources:
  DemoServerless:
    Type: AWS::Serverless::Function
    Properties:
        Runtime: python3.9
        Handler: function.lambda_handler
        CodeUri: ./my-deployment-package.zip
        PackageType: Zip